### film id test: check response for id 1
GET http://localhost:8080/api/v1/films/1
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.filmId === 1, "Film id is not 1");
        client.assert(response.body.title === "ACADEMY DINOSAUR", "Title is not 'ACADEMY DINOSAUR'");
    });
%}
